
voice_assistant:
    keywords:
      - text: "hey google"
        sensitivity: 1
      - text: "ok google"
        sensitivity: 1
      - text: "google"
        sensitivity: 1
    reply_on_keyword_detection: false # true if the voice assistant should always say something like "im listening" when its keyword is detected

wit:
  intents:
    - "date"
    - "time"
    - "wit$cancel"
    - "wit$get_weather"
    - "feit_smart_lights"


plugins:
  weather:
    enabled: false
    physical_device: false # Defines if this plugin uses or interacts with physical IoT devices.
  temporal_handler:
    enabled: true
    physical_device: false
  hue_smart_lights:
    enabled: true
    physical_device: true
  feit_electric_smart_lights:
    enabled: true
    physical_device: true
  date_handler:
    enabled: true
    physical_device: false
  cancel_handler:
    enabled: true
    physical_device: false