
voice_assistant:
    keywords:
      - text: "hey google"
        sensitivity: 1
      - text: "ok google"
        sensitivity: 1
      - text: "google"
        sensitivity: 1
    reply_on_keyword_detection: false # true if the voice assistant should always say something like "im listening" when its keyword is detected

wit:
  intents:
    - "date"
    - "time"
    - "wit$cancel"
    - "wit$get_weather"