
voice_assistant:
    keywords:
      - text: "hey google"
        sensitivity: 1
      - text: "ok google"
        sensitivity: 1
      - text: "google"
        sensitivity: 1
    reply_on_keyword_detection: false # true if the voice assistant should always say something like "im listening" when its keyword is detected

wit:
  intents:
    - "date"
    - "time"
    - "wit$cancel"
    - "wit$get_weather"
    - "feit_smart_lights"


plugins:
  weather:
    enabled: false
  time:
    enabled: true
  hue_smart_lights:
    enabled: true
  feit_electric_smart_lights:
    enabled: true
  date:
    enabled: true
  cancel:
    enabled: true