
voice_assistant:
    keywords:
      - text: "hey google"
        sensitivity: 1
      - text: "ok google"
        sensitivity: 1
      - text: "google"
        sensitivity: 1

wit:
  intents:
    - "date"
    - "time"
    - "wit/cancel"